### ISSUE TITLE
optional/autofetch description

### ISSUE THREAD

**Issue by drbig** [tj/bm#13]
I usually put more value on tags than description, so the current argument order is not the most efficient for me.

I'm proposing the following changes:

 - Optional description via an argument for add: `bm add -d "desc" link tag tag tag...`
 - Option to fetch and use the contents of `<title>` for description: `bm add -t link tag tag tag...`

**Comment by Flyounet** [comment]
You should try the last commit 1a24a40 as it seems it has what you require.
