### ISSUE TITLE
question:: full text search

### ISSUE THREAD

**Issue by directorscut82** [tj/bm#24]
if i am lazy and not use description, tag, or accelerator, does it search through the (bookmarked) site contents?

thanks

**Comment by Flyounet** [comment]
Sure you could.

Here is an example, searching for the tag `ascii` :

    : █ [0] flyou @ Blenno ~ [P:300/N:42/I:15]
    : █ 20:20:10 #1969 $; bm -s +ascii
    :29 --> DIagrams Through Ascii Art [ascii,tool,diagram,html]
    http://ditaa.sourceforge.net - Added: 2016-03-07T18:00:47Z
    
    :62 --> Chris.com - ASCII ART - Border - Borders [ascii,art]
    http://chris.com/ascii/index.php?art=art%20and%20design/borders - Added: 2016-04-22T23:40:45Z

Here is the search for the term `ditaa` :

    : █ [0] flyou @ Blenno ~ [P:300/N:42/I:15]
    : █ 20:20:59 #1970 $; bm -s ditaa
    :29 --> DIagrams Through Ascii Art [ascii,tool,diagram,html]
    http://ditaa.sourceforge.net - Added: 2016-03-07T18:00:47Z

And the search for the term `diagram` :
```
: █ [0] flyou @ Blenno ~ [P:300/N:42/I:15]
: █ 20:21:13 #1971 $; bm -s diagram
:26 --> Flowchart software | Diagram software | Flowchart diagram [online,diagram,html]
http://diagramo.com - Added: 2016-03-07T16:55:51Z

:27 --> PlantUML : Open-source tool that uses simple textual descriptions to draw UML diagrams. [online,tool,diagram,html]
http://fr.plantuml.com - Added: 2016-03-07T16:56:14Z

:28 --> PlantUML Web Server [online,tool,diagram,html]
http://plantuml.com/plantuml/ - Added: 2016-03-07T17:59:12Z

:29 --> DIagrams Through Ascii Art [ascii,tool,diagram,html]
http://ditaa.sourceforge.net - Added: 2016-03-07T18:00:47Z

:34 --> GitHub - andresmrm/EtherPlant: A simple web page to code in Etherpad and visualize in PlantUML. [tool,diagram,plantuml,etherpad]
https://github.com/andresmrm/EtherPlant - Added: 2016-03-13T23:34:04Z
```

In fact, the search is a full text search by default.

**Comment by directorscut82** [comment]
thanks for your response.. In fact after [kifi moving to google](https://news.ycombinator.com/item?id=12082239#12089982) -comments are mostly mine, i have very little luck finding a free service which does full content search (with)in the bookmared url. Chrome bookmarks despite the updates in their search engine work only with the obvious titles and tags, while the cheapest option (pinboard) do not allow sharing.
i like cli convenience, so yours is an unexpected solution (free+offlne)

Thanks again
