### ISSUE TITLE
Example errors out with "URL seems invalid"

### ISSUE THREAD

**Issue by roytruelove** [tj/bm#25]
_(v0.6.4, debian jessie)_

Running this (from the readme)

`bm add http://subtlepatterns.com "tiling background images" design textures`

yields

`Your URL seems invalid 'add'. Use -F to force.`

I've made sure all of the dependencies listed in the Readme are included.  What up?

**Comment by Flyounet** [comment]
Hi,

You are right.

Before I propose the correction, You could use the following command :

     bm -a http://subtlepatterns.com -T "tiling background images" -t design,textures

**Comment by Flyounet** [comment]
Please, have a try on the following branch : https://github.com/Flyounet/bm/tree/hotfix-issue-25

**Comment by Flyounet** [comment]
Hi,

Please update to the last master v0.6.7. It should correct your error.

Thanks for your report.
